// <auto-generated />
using System;
using KuberaManager.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace KuberaManager.Migrations
{
    [DbContext(typeof(kuberaDbContext))]
    [Migration("20201112073537_InstallDatabase")]
    partial class InstallDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("KuberaManager.Models.Database.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ContinueScenario")
                        .HasColumnType("text");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMember")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrefStartTimeDay")
                        .HasColumnType("integer");

                    b.Property<int>("PrefStopTimeDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("KuberaManager.Models.Database.AccountCompletionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("Definition")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AccountCompletionData");
                });

            modelBuilder.Entity("KuberaManager.Models.Database.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("DisableModelRendering")
                        .HasColumnType("boolean");

                    b.Property<bool>("DisableSceneRendering")
                        .HasColumnType("boolean");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LowCpuMode")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxClients")
                        .HasColumnType("integer");

                    b.Property<bool>("SuperLowCpuMode")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("KuberaManager.Models.Database.Config", b =>
                {
                    b.Property<string>("ConfKey")
                        .HasColumnType("text");

                    b.Property<string>("ConfValue")
                        .HasColumnType("text");

                    b.HasKey("ConfKey");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("KuberaManager.Models.Database.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("TextId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("KuberaManager.Models.Database.EventLogText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventLogTexts");
                });

            modelBuilder.Entity("KuberaManager.Models.Database.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("ForceRunUntilComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<string>("ScenarioIdentifier")
                        .HasColumnType("text");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("TargetDuration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("KuberaManager.Models.Database.Levels", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AccountId")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("Agility")
                        .HasColumnType("integer")
                        .HasColumnName("Agility");

                    b.Property<int>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("Attack");

                    b.Property<int>("Construction")
                        .HasColumnType("integer")
                        .HasColumnName("Construction");

                    b.Property<int>("Cooking")
                        .HasColumnType("integer")
                        .HasColumnName("Cooking");

                    b.Property<int>("Crafting")
                        .HasColumnType("integer")
                        .HasColumnName("Crafting");

                    b.Property<int>("Defence")
                        .HasColumnType("integer")
                        .HasColumnName("Defence");

                    b.Property<int>("Farming")
                        .HasColumnType("integer")
                        .HasColumnName("Farming");

                    b.Property<int>("Firemaking")
                        .HasColumnType("integer")
                        .HasColumnName("Firemaking");

                    b.Property<int>("Fishing")
                        .HasColumnType("integer")
                        .HasColumnName("Fishing");

                    b.Property<int>("Fletching")
                        .HasColumnType("integer")
                        .HasColumnName("Fletching");

                    b.Property<int>("Herblore")
                        .HasColumnType("integer")
                        .HasColumnName("Herblore");

                    b.Property<int>("Hitpoints")
                        .HasColumnType("integer")
                        .HasColumnName("Hitpoints");

                    b.Property<int>("Hunter")
                        .HasColumnType("integer")
                        .HasColumnName("Hunter");

                    b.Property<int>("Magic")
                        .HasColumnType("integer")
                        .HasColumnName("Magic");

                    b.Property<int>("Mining")
                        .HasColumnType("integer")
                        .HasColumnName("Mining");

                    b.Property<int>("Prayer")
                        .HasColumnType("integer")
                        .HasColumnName("Prayer");

                    b.Property<int>("Ranged")
                        .HasColumnType("integer")
                        .HasColumnName("Ranged");

                    b.Property<int>("Runecrafting")
                        .HasColumnType("integer")
                        .HasColumnName("Runecrafting");

                    b.Property<int>("Slayer")
                        .HasColumnType("integer")
                        .HasColumnName("Slayer");

                    b.Property<int>("Smithing")
                        .HasColumnType("integer")
                        .HasColumnName("Smithing");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("Strength");

                    b.Property<int>("Thieving")
                        .HasColumnType("integer")
                        .HasColumnName("Thieving");

                    b.Property<int>("Woodcutting")
                        .HasColumnType("integer")
                        .HasColumnName("Woodcutting");

                    b.HasKey("AccountId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("KuberaManager.Models.Database.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveComputer")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RspeerSessionTag")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("TargetDuration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("KuberaManager.Models.PageModels.ManualSession", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ComputerId")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedScenario")
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.ToTable("ManualSession");
                });
#pragma warning restore 612, 618
        }
    }
}
